### PR TITLE
Modify Cp to Symbolic link

### PR DESCRIPTION
**Pull request by kiwamunet**
I want to change `package-dir`  when I change code with `reload true` setting of `internal/watch`
Please review.

### CODE REVIEW

**Comment by seagullbird** [comment]
@pjvds Please, why is this pr still not merged? 
Cost me a whole afternoon to find this pr...

WERCKER doesn't mount the project to `$GOPATH/src/github.com/$USER/` but to `/pipeline/source`, thus reload will reload changes into `/pipeline/source` but not `$GOPATH/src/github.com/$USER`.
If you use `cp`, any changes you made after running `wercker dev` with 

```yaml
internal/watch:
    code: go run main.go
    reload: true
```

 will never make it to `$GOPATH/src/github.com/$USER/<your project>`, which is just the path where `go run main.go` is executed. You have to keep `/pipeline/source` and `$GOPATH/src/github.com/$USER/<your project>` sync all the time to support "reload".

@kiwamunet Hope I am translating you right.

**Comment by pjvds** [comment]
@seagullbird I feel sorry for you lost afternoon. I would love to pull this fix into the repository, but unfortianltly I don't have access anymore since I left wercker.

@hatchan or @mies, can one of you look at this one and make sure the problem get resolved?

**Comment by seagullbird** [comment]
@pjvds That is so kind of you. Thanks for the help.

Now I am thinking maybe using symbolic link isn't a best solution to this issue. Maybe we can add a parameter indicating using symbolic link or not? Developers can active this parameter when they need a hot reload while builds and deploys remain the same.

**Comment by hatchan** [comment]
@seagullbird Go really doesn't like symbolic links. We've had symbolic links before and reverted it. 

I recommend overriding the `base-path` like this:

```
box: golang
build:
  base-path: /go/src/github.com/wercker/step-setup-go-workspace # change according to your own repository
  steps:
...
```

This way you do not have to use this step anymore. Closing.

**Pull request closed without merging**
